CREATE TABLE [OrderItem]
(
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,--GUID 
[OrderId] UNIQUEIDENTIFIER NOT NULL, --GUID
[ProductId] UNIQUEIDENTIFIER NOT NULL, --GUID
[Quantity] DECIMAL(10,2) NOT NULL,
[Price] MONEY NOT NULL,
FOREIGN KEY([OrderId]) REFERENCES [Order]([Id]),
FOREIGN KEY([ProductId]) REFERENCES [Product]([Id])
)